### ISSUE TITLE
oc.geo.set_lat_lon() doesn't work

### ISSUE THREAD

**Issue by JaccoHoogewoud** [ArtesiaWater/hydropandas#174]

**Comment by JaccoHoogewoud** [comment]
ik heb een oc gemaakt, en wil hier een interactieve kaart mee maken volgens het voorbeeld van de website:

oc.geo.set_lat_lon()
oc.plots.interactive_map(plot_dir="figure")

maar het eerste commando loopt vast:
oc.geo.set_lat_lon()
Traceback (most recent call last):

  File "<ipython-input-11-c7e60751760c>", line 1, in <module>
    oc.geo.set_lat_lon()

  File "C:\Users\jacco\Anaconda3\envs\imod\lib\site-packages\hydropandas\extensions\geo.py", line 80, in set_lat_lon
    df_lat_lon = self._obj.geo.get_lat_lon(in_epsg, out_epsg)

  File "C:\Users\jacco\Anaconda3\envs\imod\lib\site-packages\hydropandas\extensions\geo.py", line 108, in get_lat_lon
    df_lat_lon.loc[iname, ["lat", "lon"]] = o.geo.get_lat_lon(in_epsg, out_epsg)

  File "C:\Users\jacco\Anaconda3\envs\imod\lib\site-packages\pandas\core\generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)

AttributeError: 'Series' object has no attribute 'geo'
